language: csharp
mono: latest
solution: DmarcRua.sln

install:
 - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
 - mono nuget.exe restore DmarcRua.sln
 - mono nuget.exe install NUnit.Runners -OutputDirectory testrunner
 - mono nuget.exe install Nunit3TestAdapter -OutputDirectory testrunner
 - mono nuget.exe install Microsoft.NET.Test.Sdk -OutputDirectory testrunner
