language: csharp
mono: latest
dotnet: 2.0.0
solution: DmarcRua.sln

install:
 - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
 - mono nuget.exe restore DmarcRua.sln
 - mono nuget.exe install NUnit.Runners -OutputDirectory testrunner

script:
 - msbuild DmarcRua.sln /p:Configuration=Release
 - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./DmarcRuaTests/bin/Release/netcoreapp2.0/DmarcRua.Tests.dll
 - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./DmarcRuaTests/bin/Release/net45/Dmarc.RuaTests.dll
 - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./DmarcRuaTests/bin/Release/net461/DmarcRua.Tests.dll
 - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./DmarcRuaTests/bin/Release/net462/DmarcRua.Tests.dll
